### ISSUE TITLE
找不到模块“@/public/static/charting_library”或其相应的类型声明。

### ISSUE THREAD

**Issue by DaiDaMao1** [discountry/tradingview-okx#1]
找不到模块“@/public/static/charting_library”或其相应的类型声明。

**Comment by discountry** [comment]
请仔细阅读 readme，你需要获取 https://github.com/tradingview/charting_library/ 项目的访问权限，如果没有权限可以通过官网申请：https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/
